-- AlterTable
ALTER TABLE `build` MODIFY `motherboard` VARCHAR(191) NULL,
    MODIFY `processor` VARCHAR(191) NULL,
    MODIFY `ram` VARCHAR(191) NULL,
    MODIFY `gpu` VARCHAR(191) NULL,
    MODIFY `psu` VARCHAR(191) NULL,
    MODIFY `casing` VARCHAR(191) NULL,
    MODIFY `casingPrice` DOUBLE NULL,
    MODIFY `gpuPrice` DOUBLE NULL,
    MODIFY `motherboardPrice` DOUBLE NULL,
    MODIFY `processorPrice` DOUBLE NULL,
    MODIFY `psuPrice` DOUBLE NULL,
    MODIFY `ramPrice` DOUBLE NULL,
    MODIFY `totalPrice` DOUBLE NULL,
    MODIFY `fan1Price` DOUBLE NULL,
    MODIFY `fan2Price` DOUBLE NULL,
    MODIFY `fan3Price` DOUBLE NULL,
    MODIFY `fan4Price` DOUBLE NULL,
    MODIFY `accessories1Price` DOUBLE NULL,
    MODIFY `accessories2Price` DOUBLE NULL,
    MODIFY `accessories3Price` DOUBLE NULL,
    MODIFY `accessories4Price` DOUBLE NULL,
    MODIFY `cooler` VARCHAR(191) NULL,
    MODIFY `coolerPrice` DOUBLE NULL,
    MODIFY `accessories5Price` DOUBLE NULL,
    MODIFY `storage1` VARCHAR(191) NULL,
    MODIFY `storage1Price` DOUBLE NULL,
    MODIFY `storage2Price` DOUBLE NULL;
